# Generated by Django 3.2 on 2021-12-21 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_books_sprice'),
        ('store', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='', max_length=50)),
                ('status', models.IntegerField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=True)),
                ('price', models.FloatField(default=True)),
                ('book', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.books')),
                ('order', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
    ]
