# Generated by Django 3.2 on 2021-12-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.IntegerField(default=True),
        ),
    ]
