# Generated by Django 3.2 on 2021-12-28 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_coupon_coupon_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='store.coupon'),
            preserve_default=False,
        ),
    ]
