# Generated by Django 3.2 on 2021-12-28 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_books_sprice'),
        ('store', '0014_alter_cart_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.category'),
        ),
    ]
