# Generated by Django 3.2 on 2021-12-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_cart_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon_entry',
            name='discount_price',
            field=models.FloatField(default=False),
        ),
    ]
