# Generated by Django 3.2 on 2021-12-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_buynow'),
    ]

    operations = [
        migrations.AddField(
            model_name='buynow',
            name='is_coupon',
            field=models.BooleanField(default=False),
        ),
    ]
