# Generated by Django 3.2 on 2022-01-02 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_buynow_is_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='category',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='category',
        ),
    ]
