# Generated by Django 3.2 on 2022-01-12 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0026_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='guest_user',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
