# Generated by Django 2.2.12 on 2021-12-08 13:35

import adminpanel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=adminpanel.models.filepath),
        ),
    ]
