# Generated by Django 2.2.12 on 2021-12-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_auto_20211209_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='desc',
            field=models.TextField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='books',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.FloatField(default=1),
        ),
    ]
