# Generated by Django 3.2 on 2021-12-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_auto_20211211_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='language',
            field=models.TextField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.TextField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='books',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
