# Generated by Django 3.2 on 2021-12-11 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_auto_20211211_0629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='Category',
        ),
    ]
