# Generated by Django 3.2 on 2021-12-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_rename_genres_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='sprice',
            field=models.FloatField(default=1),
        ),
    ]
