# Generated by Django 3.2 on 2022-01-02 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_books_sprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=False)),
                ('Category', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.category')),
            ],
        ),
    ]
