# Generated by Django 3.2 on 2022-01-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_rename_offers_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='newoffer',
            field=models.FloatField(default=False),
        ),
    ]
