# Generated by Django 3.2 on 2022-01-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_category_newoffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='Category',
            new_name='category',
        ),
    ]
