# Generated by Django 3.2 on 2022-01-08 09:22

import adminpanel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_rename_category_offer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=adminpanel.models.filepath),
        ),
        migrations.AddField(
            model_name='books',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=adminpanel.models.filepath),
        ),
    ]
