# Generated by Django 3.2 on 2021-12-13 13:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211213_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=50, region=None, unique=True),
        ),
    ]
